### ISSUE TITLE
 Refactor and merge scripts that clean up the data into a single pipeline.

### ISSUE THREAD

**Issue by AbdBarho** [code-openness/Data#16]

**Comment by AbdBarho** [comment]
@kozae after you have done the refactoring, please create a new pull request with the code.

**Comment by AbdBarho** [comment]
closing the issue also means closing: #11 #12 #13

**Comment by kozae** [comment]
I am done with the first form for the pipeline, I think I don't have access to make a pull request

**Comment by kozae** [comment]
pull request created, after merging I am going to work on updating the readme file
