### ISSUE TITLE
Re-design the data model

### ISSUE THREAD

**Issue by AbdBarho** [code-openness/Data#19]
depends on #18 and #17

**Comment by hannahtro** [comment]
Data model based on wikidata model:

![wikidata](https://user-images.githubusercontent.com/46645533/58879951-14689680-86d7-11e9-8714-435476153327.jpg)

! non-commented arrows signify 'subclass of'

problems:
-  hierarchy not distinct: e.g. literary work is subclass of creative work and of written work, written work is subclass of creative work
- book provides most qualities needed to model the data; work contains only some properties such as title and editor, place of publication is missing; where do we store other qualities?
- for many types in the database does not exist a corresponding item in the wikidata model: inbook (book does not have quality article), paperr and papern not distinguishable (article has no ISI attribut), inreport (report does not have required quality), procceding (does not exist in wikidata)
- data publication Q17051824 exits in wikidata, is not connected to other elements

**Comment by hannahtro** [comment]
![wikidata](https://user-images.githubusercontent.com/46645533/59503820-ade73380-8ea1-11e9-904f-e635717fcf41.jpg)

**Comment by AbdBarho** [comment]
research wikidata data model to find corresponding properties to match our columns' names and publications.

**Comment by hannahtro** [comment]
|Frequency|Column in PIK data set|Wikidata property|Comment|
|---|---|---|---|
|8261|title| title P1476| 
|8258 |keywords| 
|8235| year | publication date P577 | 
|8080|authors| author P50 | 
|7796 | publisher | publisher P123 |
| 6299| startpage | number of pages P1104| merge startpage and endpage, map to number of pages |
|6034| endpage | number of pages P1104 |
|4493| journal | academic journal Q737498 | | only paperr, papern, newspaper and inbook have entry for journal; link article to journal |
|4468|x4 ( = DOI / Identifier)| DOI P356|
|3879| vol | volume P478|
|3462| issue | issue P433
|2922|place|place of publication P291|
|1656 | editors | editor P98 |
|1516| booktitle | | | only inbook, inreport, confpaper, proceedings, epup have entry for booktitle|
|1340| relation (= Serie) | part of the Series P179| 
|974| link |
|921|comment|
|385|conference|

**Comment by hannahtro** [comment]
Questions:
Where do we add P1433 venue (published in (not place))?
Where do we add P921 topic (main subject)?
What do we do with missing PIK properties?

**Comment by AbdBarho** [comment]
P1433: There some inconsistencies in how the data looks like and how Scholia requests it.
for example, in Scholia, in `author.html` we see the following request:
```sparql
?work wdt:P1433 ?venue .
```
where as on the [official page of P1433](https://www.wikidata.org/wiki/Property:P1433), the description of the item says : larger work that a given work was published in, like a book, journal or music album.
then again, a venue is the physical place where it was published, but in this case it is used as `part of`, maybe it is just a naming problem.

P921: we have the column `keywordsAndPeerReview` (also named `x1 ( =Feld ""Keyword"";  u.a. belegt mit Info zu peer-review, wenn kein ISI-Journal)`) which might be a good candidate.

For the most part we can ignore the remaining PIK properties to deliver the first prototype at time, additional input from PIK is needed for how important is this information and how it ties with the other values we have.

**Comment by AbdBarho** [comment]
author inconsistencies:
taking the following example query for the author [Didier Musso](https://www.wikidata.org/wiki/Q24244119):
```sparql
select ?work where {
  ?work wdt:P50 wd:Q24244119 .
}
````
we can see that has published some work and Scholia would recongnize him as an author, however, on his wikidata page, we find no mention of the class [author](https://www.wikidata.org/wiki/Q482980) anywhere. the only link is through the occupation property which has the value `researcher`, which in itself a subclass of  `creator` (`author` is also a subclass of `creator`)

This further leads to the assumption that all the data model is build on relationships between the different items instead of class hierarchies.

**Comment by AbdBarho** [comment]
# Initial draft of the new data model
## Publications
a publication is an [instance of (P31)](https://www.wikidata.org/wiki/Property:P31) one of the following items:
  - `paperr`: article [Q191067](https://www.wikidata.org/wiki/Q191067)
  - `papern`: article [Q191067](https://www.wikidata.org/wiki/Q191067)
  - `inbook`: chapter [Q1980247](https://www.wikidata.org/wiki/Q1980247)
  - `confpaper`: conference paper [Q23927052](https://www.wikidata.org/wiki/Q23927052)
  - `lecture`: lecture [Q603773](https://www.wikidata.org/wiki/Q603773)
  - `report`: report [Q10870555](https://www.wikidata.org/wiki/Q10870555)
  - `epup`: electronic publication [Q21572908](https://www.wikidata.org/wiki/Q21572908)
  - `inreport`: research report [Q59387148](https://www.wikidata.org/wiki/Q59387148)
  - `intseries`: technical report [Q3099732](https://www.wikidata.org/wiki/Q3099732)
  - `book`: book [Q571](https://www.wikidata.org/wiki/Q571)
  - `newspaper`: newspaper article [Q2495037](https://www.wikidata.org/wiki/Q2495037)
  - `edbook`: edited volume [Q1711593](https://www.wikidata.org/wiki/Q1711593)
  - `data`: data publication [Q17051824](https://www.wikidata.org/wiki/Q17051824)
  - `software`: software project [Q63437139](https://www.wikidata.org/wiki/Q63437139)
  - `dipl`: diploma thesis [Q30749496](https://www.wikidata.org/wiki/Q30749496)
  - `habil`: habilitation thesis [Q1414362](https://www.wikidata.org/wiki/Q1414362)
  - `thesis`: doctoral thesis [Q187685](https://www.wikidata.org/wiki/Q187685)
  - `proceedings`: proceedings [Q1143604](https://www.wikidata.org/wiki/Q1143604)

## Authors & Editors
  - `author`: Author [Q482980](https://www.wikidata.org/wiki/Q482980)
    - `author`: a work has [author (P50)](https://www.wikidata.org/wiki/Property:P50) property
  - `editor`: Editor [Q1607826](https://www.wikidata.org/wiki/Q1607826)
    - `editor`: a work has [editor (P98)](https://www.wikidata.org/wiki/Property:P98) property

## Others
  - `publisher`: Publisher [Q2085381](https://www.wikidata.org/wiki/Q2085381)
    - `publisher`: a work is [published (P123)](https://www.wikidata.org/wiki/Property:P123) by a Publisher
  - `journal`: academic journal [Q737498](https://www.wikidata.org/wiki/Q737498)
    - `published in`: a publication is [published in (P1433)](https://www.wikidata.org/wiki/Property:P1433) a journal
  - `issue`: (literal) a publication has an [issue (P433)](https://www.wikidata.org/wiki/Property:P433)
  - `vol`: (literal) a publication has a [volume (P478)](https://www.wikidata.org/wiki/Property:P478)
  - `startpage & endpage`: literal
    - `number of pages` a publication has [number of pages (P1104)](https://www.wikidata.org/wiki/Property:P1104)
  - `DOI`: literal [DOI (P356)](https://www.wikidata.org/wiki/Property:P356)
  - `year`: literal [publication date (P577)](https://www.wikidata.org/wiki/Property:P577)
  - `[---]`: a place where a publication was published (country/city/etc...)
    - `place`: a publication has property [place of publication P291](https://www.wikidata.org/wiki/Property:P291) to the place where it was published
  - `[---]`: a series of publications
    - `series`: a publication is [part of the series (P179)](https://www.wikidata.org/wiki/Property:P179)
  - `[---]`: anything...
    - `keywords`: a publication has a list of [main subjects (P921)](https://www.wikidata.org/wiki/Property:P921)
