### ISSUE TITLE
Table of Wikidata objects

### ISSUE THREAD

**Issue by AbdBarho** [code-openness/Data#28]
create table of wikidata entities corresponding to elements/types in our data set.

provide example and explanation, something like:

|PIK|Wikidata|Example|Comment|
|---|---|---|---|

**Comment by hannahtro** [comment]
|Frequency|Type in PIK data set|Wikidata item|Example|Comment|
|---|---|---|---|---| 
3554 | paperr | article Q191067 |  Behavior of nuclear fuel during a reactor accident (Q28821) | article in Web of Science-indexed journals, WoS item in Wikidata Q1201886; additional column needed to keep information |
1376 | inbook | chapter Q1980247 | The Knight's Tale (Q2260441) | article in book, chapter is used to denote a book chapter or a book section|
849 | papern | article Q191067 |  Behavior of nuclear fuel during a reactor accident (Q28821) | article in non-WoS journal|
490 | confpaper | conference paper Q23927052 |  Ergonomic evaluation of California winegrape trellis systems (Q23909896) |document published as part of the proceedings of an academic conference|
469 | lecture | lecture Q603773 | Lectures on Faith (Q6512434)|oral presentation intended to present information or teach people about a particular subject|
377 | report | report Q10870555 | Agrarbericht (Q396036) |informational, formal, and detailed text|
352 | epup | electronic publication Q21572908 |  Computer Weekly (Q5157518) | epup signifies an electronic publication such as blog entries; no item description available in wikidata |
221 | inreport | research report Q59387148 |  Calculated Ambiguity: Nuclear weapons and the Gulf War (Q63919049) | no corresponding item in wikidata, use research report for simplicity, no item description available in wikidata|
132 | intseries |  technical report Q3099732 |  Silica dust test for respiratory protective devices (Q26374883) | series of PIK,  describes the process, progress, or results of technical or scientific research|
130 | book |book Q571|Social Outsiders in Nazi Germany (Q25435)|medium for a collection of words and/or pictures to represent knowledge or a fictional story|
110 | newspaper | newspaper article Q2495037 |  The Japan of 1909 (Q63041355) |article in a newspaper, no description in wikidata, subclass of news article that denotes article that is published in news media|
102 | edbook  | edited volume Q1711593 |  Alles über Wikipedia und die Menschen hinter der größten Enzyklopädie der Welt (Q2648716)  | collection of scholarly or scientific chapters written by different authors| 
59 | thesis | doctoral thesis Q187685 |  Kritik und Krise (Q1789473) | thesis that someone wrote to obtain a PhD degree|
22 | data | data publication Q17051824 | no example | data signifies data publication, no item description available in wikidata|
12 | software |  software project Q63437139 | Robustifying Scholia (Q63437117) | can be traced at zenodo, DOI information provided; software denotes software publication; software project is project in the framework of which software is developed| 
4 | dipl |  diploma thesis Q30749496 |  Les Bibliothèques populaires du département de la Seine (1861-1945) (Q42434641) |no item description available in wikidata|
3 | proceedings | proceedings Q1143604 |  Proceedings of the Iranian National Assembly, 1947 (Q19540063) |collection of scholarly papers published in the context of an academic conference|
1 | habil |  habilitation thesis Q1414362 |  Netzwerkarchitekturen, Zielfunktionen und Kettenregel (Q58919327) | no item description available in wikidata|

**Comment by hannahtro** [comment]
Is 'electronic publication' appropriate for modelling 'epub'?
Is 'data publication' appropriate for modelling 'data'?
Is 'software project' appropriate for modelling 'software'?

**Comment by clmb** [comment]
@HannahMariechen, It looks good, but I need a list of all subclasses of Q732577 (publication). Where do you have this list? Btw, here is an explanation how to create such a list: https://github.com/wikicite/wikicite-data
